### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by DimonYoing** [Wertzui123/RenameItems#4]
Make sure that when you write /rename I was able to measure the text of the "send" button to another text

**Comment by Wertzui123** [comment]
Please clarify your comment, I can't understand it.

**Comment by DimonYoing** [comment]
Make it so that you can change the text of the button

**Comment by Wertzui123** [comment]
That's not possible in Minecraft.

**Comment by DimonYoing** [comment]
In your plugin so that you can change the text of the button that is in the UI form

**Comment by Wertzui123** [comment]
As I have already said, you cannot override this text.
It will always be "Send" in your client language.
